### PR TITLE
Various fixes for Visual Studio

### PR DESCRIPTION
**Pull request by sylvain-bougnoux**
The various fixes are in the 3 commits' title.
Normally it should not impact compilation on Linux.
However I am not sure of `feclearexcept`

### CODE REVIEW

**Comment by olivierbichler-cea** [comment]
Hi,
There is an issue with Linux because of the change in PadCropTransformation.cpp.
I suggest removing that change since a cast to (int) was already added in the latest commit.

**Comment by olivierbichler-cea** [comment]
Also, feclearexcept has not the same meaning. fedisableexcept is not supported on Windows (it's a glibc extension), so it's best to put the fedisableexcept in a #ifndef WIN32 block.

**Comment by sylvain-bougnoux** [comment]
> so it's best to put the fedisableexcept in a #ifndef WIN32 block.

Yes but does not solve #33.
What about ?
```
#ifdef WIN32
    fenv_t excepts;
    feholdexcept(&excepts);
#else
    fedisableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW | FE_UNDERFLOW);
#endif
```
I am not familiar with `feholdexcept` but according to the [docs](https://en.cppreference.com/w/c/numeric/fenv/feholdexcept), it could do the job (it sets a **non-stop mode**). Actually if it works it could be the preferred solution (no more `ifdef`)

NB: at [cplusplus.com the doc](http://www.cplusplus.com/reference/cfenv/feholdexcept/) is a bit different. They mention that the non-stop mode might not supported by all implementations....

**Comment by olivierbichler-cea** [comment]
I think your solution for floating point exception handling is good enough! I agree with you, it could be the preferred, portable way of temporary disabling FP exception. But as there is still some doubt, referring to the cplusplus doc, I suggest to keep the WIN32 flag for now, as you did.

It seems that your CMake changes broke the Linux compilation. I think this is because you should pass the -std=c++11 flag also to nvcc, not just to the C++ compiler with the -Xcompiler flag.

**Comment by sylvain-bougnoux** [comment]
> I suggest to keep the WIN32 flag for now, as you did.

Yes I think it is safer

>It seems that your CMake changes broke the Linux compilation. I think this is because you should pass the -std=c++11 flag also to nvcc, not just to the C++ compiler with the -Xcompiler flag.

Yes I know, the issue is that I don't have an easy access to a linux machine with cuda installed. Therefore I rely on travis test to see if it works (actually I could not imagine it were this sensible). 

There are several solutions:
* either the Xcompiler must be [repeated for each flag ](https://stackoverflow.com/questions/26674885/nvcc-strange-interaction-with-xcompiler).
* either the standard way to force c++11 [is](https://cmake.org/cmake/help/v3.8/prop_tgt/CUDA_STANDARD.html#prop_tgt:CUDA_STANDARD): 
`set_property(TARGET tgt PROPERTY CUDA_STANDARD 11)`
But I don't know when this was introduced (your minimum required cmake is 3.1). And it also requires the target that we don't have when the nvcc macro is called (minor issue).

**Comment by sylvain-bougnoux** [comment]
FYI Solution using CUDA_STANDARD does not work

From travis ([356.4](https://travis-ci.org/CEA-LIST/N2D2/jobs/585970819))
>/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

I will go back with -std

**Comment by vtemplier** [comment]
I close this PR.
More updates will come in the upcoming weeks to offer an N2D2 experience on Windows without compile problems.

Stay tuned for future releases :wink:

**Pull request closed without merging**
